---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################

# --- base website settings ---

title: Justin W. Flory
description: >-
  Personal website of Justin W. Flory, a student and open source contributor
  in the United States. Keeping the freedom flag high since 2011.
url: "https://jwf.io"
year: "2020"


# --- general settings ---

baseurl: ""  # the subpath of your site, e.g. /blog
github_repo: "https://github.com/jwflory/jwflory.github.io"
favicon_path: "/static/favicon.ico"
logo_path: "/static/logo.jpg"

# Are you looking for new opportunities? Set hire_me to "true" if you want your
# LinkedIn to show on the nav bar and for boilerplate text on how to get in
# touch with me.
hire_me: false


# --- biography site information ---
# https://schema.org/

name: "Justin W. Flory"
gender: "Male"
email: contact@jwf.io
blog: https://blog.jwf.io
knows_about: >
  "Justin W. Flory",
  "jflory7",
  "jwf",
  "student",
  "open source",
  "RIT",
  "Rochester Institute of Technology",
  "Fedora Project",
  "UNICEF"

# -- social media --
github_username: jwflory
lastfm_username: jflory7
linkedin_url: justinwflory
twitter_username: jflory7


# --- build settings ---

markdown: kramdown
permalink: pretty  # no .html extensions
plugins:
  - jekyll-feed
  - jekyll-sitemap
theme: minima


# --- exclusions ---
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - node_modules/
  - Rakefile
  - README.md
  - tmp
  - vendor
